Remove left_right from text-underline-position
openwebdocs/mdn-bcd-collector pull request #847
Opened 2023-11-15 14:36 UTC by Elchi3

Was removed in BCD in https://github.com/mdn/browser-compat-data/pull/21022

2023-11-17 20:15 UTC, queengooborg requested changes

2023-11-17 20:15 UTC, queengooborg commented on custom/css.json
> +        "above_below": ["above", "below"]
We should also remove `above_below` and add the individual entries following what we discussed in the BCD PR as well.

2023-11-20 10:06 UTC, Elchi3 commented on custom/css.json
>        },
```suggestion
```

2023-11-23 05:03 UTC, queengooborg approved these changes

2023-11-23 05:03 UTC, merged