Collect Selenium results for beta browsers
openwebdocs/mdn-bcd-collector pull request #951
Opened 2023-12-13 18:58 UTC by Elchi3

I've been manually collecting results on beta browsers but ideally we want to collect results automatically. I think this PR should do that.
This will help to reduce manual BCD PRs that people usually submit during the beta phase of browsers. See also https://github.com/mdn/community-meetings/blob/main/23-12-11/minutes.md#bcd where Ruth asked about this.

2024-05-31 08:30 UTC, Elchi3 commented
In Beta browsers there are sometimes A/B tests which can skew the test results.

For Chrome, I found https://chromium.googlesource.com/chromium-variations/ and so `open -a Google\ Chrome\ Beta --args --fake-variations-channel=stable` should hopefully disable the variation and make Beta act like a stable browser release. Is it somehow possible to tell Selenium to launch Chrome beta with `--fake-variations-channel=stable`?
(https://github.com/mdn/browser-compat-data/pull/23207#issuecomment-2141479252)

For Firefox, something similar exists, but I haven't done the research yet how to prevent it from happening there.

2024-06-11 17:46 UTC, queengooborg requested changes
`filterVersions` is also used in the `find-missing-reports` script, which notifies us if there is any critical report files missing.  We should add a new argument that allows us to specify if we want to include beta releases.

One of my other concerns is that we have no way of tracking if a report came from a beta or stable version of the browser, which could potentially skew our results when running the `update-bcd` script.  It would also make it harder to know if we need to re-run the collector on the stable version of the browser and obtain support results from a stable release.  If we could update the filename saved by the Selenium script to clarify it's for a beta release, that would be helpful.

2024-11-14 13:23 UTC, caugner commented
> One of my other concerns is that we have no way of tracking if a report came from a beta or stable version of the browser,

See: https://github.com/openwebdocs/mdn-bcd-collector/pull/1957

PS: Another way would be to amend the result export with the browser release data, i.e. adding a key `release` after the `userAgent` key.

2026-06-19 16:56 UTC, Elchi3 commented on lib/filter-versions.ts
>    for (const [version, versionData] of releases) {
Played a bit more with this and the beta needs to actually make it into the array

```
if (versionData.status == "beta") {
      versions.push(version);
    }
```

See also, https://webdriver.io/docs/capabilities/#automate-different-browser-channels where "beta" itself might be an available version number. 

This all didn't work so well in my testing, though. Closing for now.

2026-06-19 16:56 UTC, closed without merging